apiVersion: v1
kind: Namespace
metadata:
  name: v6-node

---
apiVersion: v1
kind: Namespace
metadata:
  name: v6-jobs

---
apiVersion: v1
kind: Pod
metadata:
 name: poc-node-pod
 namespace: v6-node
spec:
 containers:
 - name: dummy-node-server
   image: docker.io/hectorcadavid/dummy_node_x86:latest
   tty: true
   env:
   - name: HOST_IP
     valueFrom:
       fieldRef:
         fieldPath: status.hostIP
   - name: PORT
     value: "5000"
   command: ["python", "node.py"]
   volumeMounts:
   - name: task-files-root
     mountPath: /app/tasks
   - name: kube-config-file
     mountPath: /app/.kube/config  
   - name: v6-node-config-file
     mountPath: /app/.v6node/node_config.yaml

 volumes:
 - name: task-files-root
   hostPath:
     path: /tmp/tasks
 - name: kube-config-file
   hostPath:
     path: /home/hcadavid/.kube/config   
 - name: v6-node-config-file
   hostPath:
     path: /home/hcadavid/k8s/v6-on-kubernetes-PoC/node_poc/node_config.yaml

